// @ts-check
/**
 * Generates public/_headers from the single source of truth in securityHeaders.js,
 * so static hosts (Netlify, Cloudflare Pages) enforce the same headers the Node
 * server sends. Wired into `build:prebuild`; safe to run standalone.
 */
const fs = require("fs");
const path = require("path");

const { securityHeaders } = require("./securityHeaders");

const outFile = path.join(__dirname, "..", "public", "_headers");
const body = [
  "# AUTO-GENERATED by scripts/genHeaders.js from scripts/securityHeaders.js — do not edit by hand.",
  "/*",
  ...securityHeaders.map(({ key, value }) => `  ${key}: ${value}`),
  "",
].join("\n");

fs.writeFileSync(outFile, body);
// eslint-disable-next-line no-console
console.log(`Generated ${path.relative(path.join(__dirname, ".."), outFile)}`);
